Dev
Goodidea-backend-camp/BE11-pokemon-wade-backend pull request #2
Opened 2023-11-07 10:53 UTC by SUPERWADELEE

1. 修改註冊功能：
    設定發送註冊信功能，以及設定queue讓使用者發信後不用等待太久
    新增驗證邏輯
    
2.修改第三方登入功能：
    新增第三方登入id欄位，方便註冊的時候可以做判斷。
    
3.修改寶可夢種族(商品)主頁返回資料：
   主要將routes改為不用登入使用者就可以瀏覽商品

2023-11-07 11:05 UTC, JYu1999 requested changes
Done

2023-11-07 11:05 UTC, JYu1999 commented on app/Http/Controllers/GoogleLoginController.php
> +            return response()->json(['error' => '無法重定向到Google。請稍後再試。'], 500);
錯誤訊息請另外拆出去放

2023-11-07 11:05 UTC, JYu1999 commented on app/Http/Controllers/GoogleLoginController.php
> +     public function handleProviderCallback()
這個 method 太長了，請拆部分邏輯去 service

2023-11-07 11:05 UTC, JYu1999 commented on app/Http/Controllers/RegisterController.php
> +        return response(['message' => 'User successfully registered.'], Response::HTTP_CREATED);
訊息請拆出去放

2023-11-07 11:05 UTC, JYu1999 commented on app/Http/Controllers/RegisterController.php
> +    public function register(RegisterRequest $request)
這個 function 邏輯太多，請拆去 service 做

2023-11-07 11:05 UTC, JYu1999 commented on app/Models/User.php
> +    }
為什麼這個 function 要放在 model？

2023-11-07 11:05 UTC, JYu1999 commented on config/success_messages.php
> +    "Email_Verification"=>'Email already verified.'
請統一使用大寫

2023-11-07 11:05 UTC, JYu1999 commented on database/migrations/2023_11_07_075143_make_password_nullable_in_users_table.php
> +            $table->string('password', 255)->nullable()->change();
系統還沒有正式上線前，其實不太需要用到 change，直接改原本的 migration 就好了

2023-11-08 00:49 UTC, SUPERWADELEE commented on app/Models/User.php
> +    }
當User model 使用了MustVerifyEmail trait
在創建user實例的時候，就可以去調用一些發送驗證信的方法
包括sendEmailVerificationNotification

那這裡為什麼要在User Model寫這個方法是因為，如果你沒有做任何操作就直接去調用此方法，
那就是預設會幫你發一個laravel 預設的信，
但如果你今天想對信的內容做一些操作，就可以在這裡面去複寫他，
比如這裡又去調用了我自己寫的notification裡面的一個VerifyEmail class
然後我就可以在裡面定義信件的一些比如subjet還有view

2023-11-08 05:11 UTC, JYu1999 reviewed
Done

2023-11-08 05:11 UTC, JYu1999 commented on app/Http/Controllers/GoogleLoginController.php
> +            return response()->json(['error' => config('error_messages.REDIRECTFAILED')], Response::HTTP_INTERNAL_SERVER_ERROR);
redirect 和 failed 是兩個不同的字，請用底線區隔

2023-11-08 05:11 UTC, JYu1999 commented on app/Services/RegisterService.php
> +        return ['message' => config('error_messages.EMAILHASREGISTERED'), 'status' => Response::HTTP_CONFLICT];
不同單字請用底線區隔

2023-11-08 05:14 UTC, JYu1999 commented on app/Models/User.php
> +    }
@SUPERWADELEE 
我的意思是，在我的認知裡面，與資料庫操作相關的邏輯，才會放到 model 裡面。
notify 這件事情，跟 model 的關係較小，如果要寄信的話，是不是用 event listener 實作會比較恰當呢？

2023-11-08 05:14 UTC, JYu1999 commented on database/migrations/2023_11_07_075143_make_password_nullable_in_users_table.php
> +            $table->string('password', 255)->nullable()->change();
@SUPERWADELEE 請問這個有修改了嗎？建議改一下，不然到時候 migration 會變超多

2023-11-08 06:14 UTC, SUPERWADELEE commented on app/Models/User.php
> +    }
後來發現我其實有在listener裡面呼叫VerifyEmail class，所以model那段是多寫了，而且確實也沒有必要。

2023-11-08 06:15 UTC, JYu1999 commented on app/Models/User.php
> +    }
水喔

2023-11-08 07:06 UTC, JYu1999 requested changes
Done

2023-11-08 07:06 UTC, JYu1999 commented on app/Models/User.php
> +    // }
不需要的 code 請直接刪除

2023-11-08 07:15 UTC, JYu1999 approved these changes
Done

2023-11-09 15:53 UTC, Jheng-github reviewed
hahaha

2023-11-09 15:53 UTC, Jheng-github commented on app/Services/RegisterService.php
> +
給個小建議 email基本上也是唯一值 也可以考慮透過 傳遞id 在select email的方式 
效率會比較好 id 本身自帶index 搜尋效果是比較好的
不過這取決於目前專案整體架構 給個意見XD
因為如果是下where first. 他等於會一筆一筆往下不斷尋找 如果他是第一萬個使用者 前面就會多跑9999筆

2023-11-09 15:53 UTC, Jheng-github commented on app/Services/RegisterService.php
> +
光看handleExistingUser 我不知道他是在處理更新帳號密碼

2023-11-09 15:53 UTC, Jheng-github commented on app/Services/RegisterService.php
> +    }
建議有hard code 字串的地方用常數替代

2023-11-09 16:10 UTC, Jheng-github commented on app/Services/RegisterService.php
> +
然後 如果protected function 意味不能接受被修改 想要藏起來 而同時你又包裝了這個單獨的method
我要改還是很容易啊XD 跟你設定public 是差不多意思的我覺得
1.另外拉成一包繼承 
2.乾脆就直接下在主要語法裡面不包裝 
3.用use引入也可以(?

2023-11-10 04:39 UTC, JYu1999 commented on app/Services/RegisterService.php
> +
好奇，什麼是「傳遞 id 再 select Email」 的方式

2023-11-11 06:17 UTC, SUPERWADELEE commented on app/Services/RegisterService.php
> +
我對於protected目前理解的用法是，如果今天有method，是只要給class內部呼叫的時候會用到的。
例子：
比如說我這個例子的下面有一個protected function createNewUser，我今天對外的method是 public function registerUser，然後我經過一些判斷(比如email存不存在)，不存在的情況我才會去呼叫那個function 做新增，
那我今天如果是讓外部可以直接訪問，就可能會繞過這個判斷，但在我的情境下這樣會讓我的邏輯錯誤。

我目前的理解。

2023-11-11 06:27 UTC, JYu1999 commented on app/Services/RegisterService.php
> +
只有給 class 內部呼叫，那為什麼不用 private 就好呢？

2023-11-11 06:39 UTC, SUPERWADELEE commented on app/Services/RegisterService.php
> +
Protect 可能就是讓之後繼承的class 可以引用這些方法，雖然目前的需求沒有，但先保持彈性？

2023-11-11 08:59 UTC, SUPERWADELEE commented on app/Services/RegisterService.php
> +
感謝提醒！
確實我原本的handleExistingUser()
的ExistingUser有點混搖：
因為我判斷是否有該使用者是在call這個function 前，動作也不夠明確。

我這個功能他是在判斷說，
今天使用者輸入的密碼不存在，那我讓他更新密碼（因為這代表他可能用過第三方登入）， 如果已存在代表他註冊過了（則不做更新），
請問我function的名稱取名比如handleUserPassword（）合適嗎？
因為我是針對password 做判斷並做了兩種處理。

2023-11-12 07:28 UTC, JYu1999 commented on app/Services/RegisterService.php
> +
Okkkk

2023-11-18 03:03 UTC, JYu1999 reviewed
沒問題，等功能拔掉後即可 merge

2023-11-18 03:07 UTC, JYu1999 commented on app/Services/RegisterService.php
> +
@SUPERWADELEE 如果改完了要主動回報在 comment 喔～

2023-11-18 03:12 UTC, JYu1999 reviewed
突然看到

2023-11-18 03:12 UTC, JYu1999 commented on config/success_messages.php
> +    "REGISTER_SUCCESSFULLY"=>'User successfully registered'
為什麼會有兩個 `REGISTER_SUCCESSFULLY`?

2023-11-18 03:24 UTC, SUPERWADELEE commented on config/success_messages.php
> +    "REGISTER_SUCCESSFULLY"=>'User successfully registered'
之前使用的時候沒看清楚，已更新，感謝提醒

2023-11-18 03:25 UTC, JYu1999 reviewed
Done

2023-11-21 08:18 UTC, JYu1999 reviewed
done

2023-11-21 11:11 UTC, merged