新增結帳功能
Goodidea-backend-camp/BE11-pokemon-wade-backend pull request #4
Opened 2023-11-24 11:23 UTC by SUPERWADELEE

一.購物車：
     將新增修改的邏輯包道service。
     刪除部分加入policy。
     在購物車頁面的部分多返回總價格。
二.金流部分：
     新增在結帳後新增訂單及訂單細節功能。
     新增在結帳後新增使用者寶可夢。
     將整個金流邏輯包道service。
     增加錯誤處理，會回給前端藍星定義的錯誤訊息。

2023-11-24 11:58 UTC, JYu1999 requested changes
- method 請盡量指定 arguments 和回傳的 type
- 數字請勿 hard code

2023-11-24 11:58 UTC, JYu1999 commented on app/Providers/AuthServiceProvider.php
> +        // });
不需要的 code 請直接移除

2023-11-24 11:58 UTC, JYu1999 commented on app/Models/Order.php
>      ];
盡量避免在 `$fillable` 塞入過多 column，避免 [Mass Assignment](https://laravel.com/docs/10.x/eloquent#mass-assignment)

2023-11-24 11:58 UTC, JYu1999 commented on app/Models/Order.php
> +            // ... 如果還有其他的映射，你可以繼續添加
盡量避免直接使用數字，這樣到時候 debug 會比較麻煩。
而且 `$statuses` 這個命名有點怪

2023-11-24 11:58 UTC, JYu1999 commented on app/Models/Order.php
> +        ];
避免直接使用數字 + 修改 array 名稱

2023-11-24 11:58 UTC, JYu1999 commented on app/Models/Order.php
> +        return $statuses[$value] ?? $value;
避免直接使用數字 + 修改 array 名稱

2023-11-24 11:58 UTC, JYu1999 commented on app/Models/Order.php
> +        return $statuses[$value] ?? $value;
話說 `Processed` 是已處理完，你的意思確定是這樣嗎？如果確定要不要改成 `Done` 之類的

2023-11-24 11:58 UTC, JYu1999 commented on app/Services/CartItemStoreService.php
> +        $this->userId = Auth::id(); // 获取当前认证用户的ID
註解可以的話避免簡體字，有時候會遇到很在意的人...

2023-11-24 11:58 UTC, JYu1999 commented on app/Services/CartItemStoreService.php
> +        }
可以考慮 try catch 一下，避免失敗狀況：
```php
try {
    CartItem::create([
        'user_id' => $this->userId,
        'quantity' => $this->quantity,
        'current_price' => $race->price,
        'race_id' => $race->id,
    ]);

    return [
        'success' => config('success_messages.ITEM_ADD_TO_CART'), 
        'status' => Response::HTTP_OK
    ];
} catch (\Exception $e) {
    Log::error('Error adding item to cart: ' . $e->getMessage());
    
    return [
        'error' => 'Failed to add item to cart.',
        'status' => Response::HTTP_INTERNAL_SERVER_ERROR
    ];
}
```

2023-11-24 11:58 UTC, JYu1999 commented on app/Services/CartItemUpdateService.php
> +            ->selectRaw('SUM(current_price * quantity) as total')
除非必要或效能上有需求，否則盡可能不要寫 raw sql query

2023-11-24 11:58 UTC, JYu1999 commented on app/Services/NewebpayMpgResponse.php
>          $slastc = chr($slast);
這個變數的命名感覺是看藍星的文件的？通常盡可能還是把變數的名稱寫成自己看得懂，不然 debug 很麻煩

2023-11-24 11:58 UTC, JYu1999 commented on app/Services/OrderService.php
> +    }
我在想這個是不是應該用 factory？

2023-11-24 11:58 UTC, JYu1999 commented on app/Services/PaymentErrorHandlingService.php
> +        return redirect("https://wadelee.shop/order?status=$errorMessage&order=$merchantOrderNo");
網址不要 hard code，不然部署的時候忘記改就麻煩了

2023-11-24 11:58 UTC, JYu1999 commented on app/Services/PokemonCreateService.php
> +        return $skillsIdsForRace->random(min(4, $skillsIdsForRace->count()))->toArray();
數字不要 hard code

2023-11-24 11:58 UTC, JYu1999 commented on app/Services/PokemonCreateService.php
> +            'level' => rand(1, 100),
數字避免 hard code

2023-11-24 11:58 UTC, JYu1999 commented on config/error_messages.php
> +    "MPG01012" => "商店訂單編號不可空白/設定錯誤",
建議可以的話，還是統一一下語言

2023-11-25 02:59 UTC, SUPERWADELEE commented on app/Services/OrderService.php
> +    }
因為我這裡初始的訂單狀態目前是都一樣的，我也沒有在其他地方會有創建訂單的邏輯，我想不太到使用factory的理由誒？

2023-11-25 04:57 UTC, JYu1999 commented on app/Services/OrderService.php
> +    }
對 sorry 我誤解了

2023-11-25 05:33 UTC, SUPERWADELEE commented on app/Services/PokemonCreateService.php
> +            'level' => rand(1, 100),
想問這種數字要設常數或config媽？  就我目前理解如果是這個數字代表某個意義，那設常數或設定config我能理解，但我這個數字他就是數字，我不太能理解他還要設定常數的意義？

2023-11-26 04:26 UTC, SUPERWADELEE commented on app/Models/Order.php
>      ];
這個status欄位我是想說雖然現在目前沒有物流，或是其他處理，結完帳其實就等於訂單完成了，
但就是考慮到之後有其他處理比如物流的話，所以才先留著。 
目前order表裡是有這個欄位的。

2023-11-26 06:00 UTC, JYu1999 commented on app/Models/Order.php
>      ];
應該說，這和你有沒有用到無關。
不用 `$fillable` 也是可以新增值，可能就是 new 一個 model 出來，然後一個值一個值指定這樣。
例如：
```
User::create([
   "name": "John",
   "age":"18",
]);
```
變成：
```
$user = new User();
$user->name = "John";
$user->age = 18;
$user->save();
```

2023-11-26 06:02 UTC, JYu1999 commented on app/Models/Order.php
>      ];
看你自己想採用哪種方式，Laravel 預設禁用 Mass Assignment，但我們未必要按照著他的方式做

2023-11-27 05:52 UTC, JYu1999 commented on app/Models/Order.php
> +    const PAID = 2;
這裡各種 const 都放在一起有點亂，我認為可以拆一個檔案出去放（enum 之類的）

2023-11-27 05:52 UTC, JYu1999 commented on app/Models/Order.php
> +        $paymentStatuses = [
我傾向於把這樣 mapping 的加一個 prefix or postfix
例如：`$statusMap`，這樣你到時候要找比較好找，只要全域搜尋 `map` 就可以找到所有 mapping

2023-11-27 05:52 UTC, JYu1999 commented on app/Providers/AppServiceProvider.php
> -            // 正则表达式模式，包含只能中文和英文，但不能包含数字
我覺得這裡還是可以加註解說明正則在幹嘛，不然一般人不一定看得懂

2023-11-27 05:52 UTC, JYu1999 commented on app/Services/NewebpayMpgResponse.php
>  class NewebpayMpgResponse
話說 Mpg 是什麼？確定沒有 typo 嗎

2023-11-27 05:52 UTC, JYu1999 commented on app/Models/Order.php
> +    const PAID = 2;
如果不想拆出去做，也可以存成陣列。

2023-11-27 05:52 UTC, JYu1999 commented on config/error_messages.php
> +    "MPG01001" => "Member parameters cannot be empty or set incorrectly",
我覺得這部份的訊息有點太雜亂了，可以考慮 refactor 一下

2023-11-28 07:00 UTC, JYu1999 reviewed
okkk

2023-11-28 09:17 UTC, merged